#!/usr/bin/python3

from autocorrect import Speller

original_text = """CLOUDS BUT WE AJ HS ECTING MORE STORMY WEATHER TMW SO I PUSHED THE MOW AHEAD A FEW DAYS E T C E T C_ _, SO JUST TRRYING TO GIVE TI  RRLE  T CHANCE AMONG THE W E E DS HIHI _ , DOUG I HEAR YOU PRETTTM  
MDL, PEAKETG S6 WITH NO PRETMP AND S9 WITH THE PRE AMP SO WILL HAVE TO DO SOME RESEARCH TO DETERMINE WHICH READING IF EITHER IS VALID HI AND BOB IS BOOMING AS IS STEVE SO FB DE W4DBV  4 _ T B RT B R  
N AT ESYES _ 4D  TUD 5E RE TTT GUD COND I T I9S ES THE BAND II IS Q U I E T E VEN TH TUMH I H E E IIEHT N ING ON THE A P BUT NOT MAKING ANY NOISE 5ERE MUCH X _ ON UR WORK OUT SID E E S THE W_ T OO _  
BON I TS _ 0 5 EENE SOTHAT NIKE BUT TH E Y S AD WE S T I L L MG TT GET SO E S E 4 E A E WX T O OR ROW SO WI LF WI L R EAVE TT WAIT E S S E E ABOUT TH AT _ _ BUT I  I T I _ L ENJOYITM TH IS N ICE COOL 
 WX E S TH AT WHY I HAVE U A F E W WINDOWS OPEN TA _ SOT ? SO I H U E E E E T H IS NE W T UN E A GM TO BE TO O D  E TO PR ACE WH E AE E THE D ENT RON S I TS NOW ST IM GG TO HAVE T T MOUNT IT ON THE S 
 ID E OF THE R ACK C AB IN E T THAT THE A MP E S SOME OT H E R GE _ IS IT N__ I HAVE A BIE L MA TCH T_E FOR 1_ 0 M I WI L L HAVE TO AO OK L IN I 5 E E _ U INTHE REE _ _ SO I WI L L HAVE T O MOVE  T 5 
 E L MATGH TO AKE ROOM UOA THE NE E TUT E R BUT  E S FB NOUG I M GLAD U NONT HAVE R F P ROB LEMS INTS E SH AKK OF COUR S E THE G RTUND PROBAN _T E   E PROB AB LY DID NTT GET R ID OF ANY C O M M OT M  
OD E BU THE L ENM T H OF THE EAOUND IS S UCH THAT I T PUTS THE SH ACK AT  _ O L T AGE M IN I MU M BUT C UR RE N T MAX E O TH A T PROBAB LY WHY IT H E E MS BE T T E R TOW TIUT TH AT CTND I T ION MAY   
TTT BE THE S AME ON AL L BANDS ES PROBAB LY WONT BE BUT U WI LL FIND UT BO E X P E A I ME N T AT ION _ SO H W DOUG ? N J 1T E S GANG DE N 1KW      TE P  T O S T E V E WF3T DE NJ1T K DE WF3T R R OK ON 
 MOWENG TODAY NERYAN GM MAN E SUNE WESS WE WOULD GET EEOME NAIN SO I CAT MOW WITHOUT WEARENG A SAZMTT EEUIT TO KEEP FROM BRATHING A TON OF DAST ANYOTE WHO WENT BY MOULD THINK IM REAA TEY NUTS OVER    
THE VIRUI  T HA THE WEE DS ARE GROWING AND I REALLY WANT TO GET TIEE LEAUES CHOPPED UP MW AND I DO TIEENK ET WAS UR TURN NOUG SO IM GOINM TO SEND IT BACK TO U TND THE N GIVE IT TO BRYAN NJ1T ETTN DE  
WFIMT K R  VERY GOOD ON ALL EER VERY BODY COMITG IN PRETTY GOOD EVEN GOT A LITTLE GR BRYAN SENDING , B UT NEMW I AM SORT OF WORKING ON A PEICE OF WORK THAT NEEDS DOING HERE AND WS DISTRACT S A LITTLE 
 BIE HISI, YOU FELLOWS HEARD E IY OF THE OTHER FA TOUSE HIGHT EP D GSYS LIKE WOI R OR IE_OW NN7CW TAEEE  E EET  ESIY_T 9 FORR TH WEE KEND SK E DS TIEIS PAST WEE KEND DOUG BK IRR OK WELL ALSO I WNT E  
D TO ASLK ASK YOU GUK S IF YOU HAVE HEAA I ABOUT THE CLUCK IN IS THERE SOMETHING LIKE THAT GOING TO HAPPEN ? THIS ME KEND I WILL BE JUST HUNTING AROUD ON THE MORNING NET AND E VENING NE T AI E E EE I 
 MEAN SKE D , I DONT G E T EON MUC OTHER WISE BUT LAST NIGHT ON 80 METERS MOT BOTH CAPE E ERDE AND 5 B 4 I GUESS THAT ES CYPRESS OR SOME EHING TL EE E LIKE THAT SORRY I WILL PAY BETTER ATTENT IN NE T 
 ST OVER HIHI W4DBVDE NJ1T K DE W4DBV VERY GOOD AND PRETTY SOLID ON ALL _, ,  WELL  EE E_NT  OPERATEINTHEEENINGSOSOME OF THE SKEDS ARE NOT MUCH USE TO ME, BUT I DO HOPE THER ARE CFO GET TOGETHERS E   
TC _ ,  EE  ANYWA Y E__TMUCH PLANNED FOR THE WEEK ERD HR, WE  DIMHTWETO _KE MICKEY TO THE VET FOR A BAD ETR INFE_ION AND IT WAS DEEP INSIDE SO THE VET CLEANED IT OUT AND WE_ILL BE GIVING HIM MEDICINE 
 IN HIS EAN DAILY ETC SO WAS VEY GLAD TO GET AN APPOOINTMENT AND GET SUCH GREAT CARE _ I LOOKED AT SOME MT E  ESE_T  XAAYS UT THE VETS AND THEY ARE CLEARER AND WITH FINDER DETAIL THAN ANY OF THE FIMS 
 I GOT TO LOOK AT AND ACTUALLY HAD TO LOOK AT TO CHECK OAR LINE PLACEMENTS ETC SO THE LEVEL OF PET K TRE IN T5UTNOUNTRY IS FANTASTIC AND WE HAVE PRICE TRANSPARENCY AND COSTS WHILE NOT CHEAP ARE       
REASONABLE I ANSIDERING WHAT IS INVOLVED E T C E T C_ __ W_L I HAD ORDERD U _PLE O_BOTTLES OF A CZECH LIQU E U R CALLED B E CHE  E   R O3T ,E NVEYNICE STUFF BUT THE WARE HOUSE WHERE IT WAS STOOREED   
WAS DESTNOYED BY THE BIG TORNADO THAT CAME THROUGH SO IT IS AFFECTING M,ANY THINGS GREAT AND SMALL HI DE W4DBV  _ U T T E EEE U M ADE RE D A BO TT LE TF WHAT AGN ? TTT  TT TTT E TT  TT T     OH IDTNT 
 KNOW WHAT THAT IS _ E E IS TH AT SOME K ITD OF L I Q U O A _ BK K YEI, A VERY NICE ONE FROM CZECHO SLOVAKIA , ,  E_EOPLE CONSIDER IT VERY A DAXING AND I UNDERSTAND  WHEN GETTING OFF THE STATE RUN    
AIRLINES IN EASTERN EUROPE THERE WAS A ST AND THAT SOLID IT BEFORE YU EVEN LEFT THE TTRT AC HIBK BK _ E E NOTL I WI L L HAVE TO LOOK THAT9E UP _ _ ES I WENT TO B T HE D IG L I _ U T  STORE TTD AY WAS 
 NOT 4Y DUSO E BUSY BUT THE Y L OOKEN"""


spell = Speller()
corrected_text = spell(original_text)

print(corrected_text)
